# Generated by Django 2.1.3 on 2019-07-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_connent', models.TextField()),
                ('comment_reply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_addr', models.TextField()),
                ('house_price', models.FloatField()),
                ('house_intro', models.TextField()),
                ('house_type', models.CharField(max_length=100)),
                ('house_num', models.IntegerField()),
                ('house_bed', models.IntegerField()),
                ('house_bed_size', models.CharField(max_length=100)),
                ('house_describe', models.TextField()),
                ('house_status', models.CharField(max_length=300)),
                ('house_traffic', models.TextField()),
                ('house_env', models.TextField()),
                ('house_set', models.TextField()),
                ('house_have_to', models.TextField()),
                ('house_cash', models.FloatField()),
                ('house_req', models.TextField()),
                ('house_way', models.TextField()),
                ('house_debook', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_name', models.CharField(max_length=100)),
                ('men_ID_card', models.CharField(max_length=18)),
                ('men_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_enter_date', models.DateField()),
                ('order_leave_date', models.DateField()),
                ('order_price', models.FloatField()),
                ('order_fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image')),
                ('image_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tel', models.IntegerField()),
                ('user_name', models.CharField(max_length=10)),
                ('user_pwd', models.CharField(max_length=8)),
                ('user_really_name', models.CharField(default=None, max_length=10)),
                ('user_id_card', models.CharField(default=None, max_length=18)),
                ('user_birth', models.DateField(default=None)),
                ('user_addr', models.CharField(max_length=100)),
                ('user_work', models.CharField(default=None, max_length=100)),
                ('user_edu', models.CharField(default=None, max_length=100)),
                ('user_sex', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_fk_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_fk_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
    ]
