# Generated by Django 2.1.3 on 2019-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_edu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id_card',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_really_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_tel',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_work',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
