# Generated by Django 2.1.3 on 2019-07-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20190717_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_tel',
            field=models.BigIntegerField(null=True),
        ),
    ]
