# Generated by Django 2.2.3 on 2019-07-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_addr', models.TextField()),
                ('house_price', models.FloatField()),
                ('house_intro', models.TextField()),
                ('house_type', models.CharField(max_length=100)),
                ('house_num', models.IntegerField()),
                ('house_bed', models.IntegerField()),
                ('house_bed_size', models.CharField(max_length=100)),
                ('house_describe', models.TextField()),
                ('house_status', models.CharField(max_length=300)),
                ('house_traffic', models.TextField()),
                ('house_env', models.TextField()),
                ('house_set', models.TextField()),
                ('house_have_to', models.TextField()),
                ('house_cash', models.FloatField()),
                ('house_req', models.TextField()),
                ('house_way', models.TextField()),
                ('house_debook', models.TextField()),
                ('house_or', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tel', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=10)),
                ('user_pwd', models.CharField(max_length=8)),
                ('user_really_name', models.CharField(max_length=10, null=True, unique=True)),
                ('user_id_card', models.CharField(max_length=18, null=True)),
                ('user_birth', models.DateField(null=True)),
                ('user_addr', models.CharField(max_length=100, null=True)),
                ('user_work', models.CharField(max_length=100, null=True)),
                ('user_edu', models.CharField(max_length=100, null=True)),
                ('user_sex', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image')),
                ('image_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_enter_date', models.DateField()),
                ('order_leave_date', models.DateField()),
                ('order_price', models.FloatField()),
                ('order_remark', models.CharField(max_length=100, null=True)),
                ('order_sure_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_status', models.IntegerField(default=0, null=True)),
                ('order_fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
                ('order_fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_name', models.CharField(max_length=100)),
                ('men_ID_card', models.CharField(max_length=18)),
                ('men_tel', models.BigIntegerField()),
                ('men_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
                ('men_fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
                ('men_fk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.Order')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_connent', models.TextField()),
                ('comment_reply', models.TextField()),
                ('comment_fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
                ('comment_fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_fk_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.house')),
                ('collect_fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
            ],
        ),
    ]
