# Generated by Django 2.1.2 on 2019-08-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('IDcard', models.CharField(max_length=100)),
            ],
        ),
    ]
